-- Bookstore seed schema + data (~50 books)
-- Table: books
DROP TABLE IF EXISTS books;
CREATE TABLE books (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT NOT NULL,
  price REAL NOT NULL,
  stock INTEGER NOT NULL
);

INSERT INTO books (id, title, author, genre, price, stock) VALUES
(1, 'Dune', 'Frank Herbert', 'science-fiction', 18.50, 12),
(2, 'Dune Messiah', 'Frank Herbert', 'science-fiction', 14.00, 5),
(3, 'Children of Dune', 'Frank Herbert', 'science-fiction', 15.25, 0),
(4, 'God Emperor of Dune', 'Frank Herbert', 'science-fiction', 16.00, 3),
(5, 'Foundation', 'Isaac Asimov', 'science-fiction', 12.99, 20),
(6, 'Foundation and Empire', 'Isaac Asimov', 'science-fiction', 12.99, 8),
(7, 'Second Foundation', 'Isaac Asimov', 'science-fiction', 13.50, 0),
(8, 'I, Robot', 'Isaac Asimov', 'science-fiction', 9.99, 25),
(9, 'Neuromancer', 'William Gibson', 'science-fiction', 11.00, 14),
(10, 'Count Zero', 'William Gibson', 'science-fiction', 10.50, 6),
(11, 'Mona Lisa Overdrive', 'William Gibson', 'science-fiction', 11.25, 0),
(12, 'Snow Crash', 'Neal Stephenson', 'science-fiction', 16.75, 9),
(13, 'The Diamond Age', 'Neal Stephenson', 'science-fiction', 15.00, 4),
(14, 'Cryptonomicon', 'Neal Stephenson', 'science-fiction', 22.00, 7),
(15, 'The Left Hand of Darkness', 'Ursula K. Le Guin', 'science-fiction', 13.25, 11),
(16, 'The Dispossessed', 'Ursula K. Le Guin', 'science-fiction', 12.50, 2),
(17, 'Hyperion', 'Dan Simmons', 'science-fiction', 17.00, 18),
(18, 'The Fall of Hyperion', 'Dan Simmons', 'science-fiction', 17.50, 0),
(19, 'Ender''s Game', 'Orson Scott Card', 'science-fiction', 10.00, 30),
(20, 'Speaker for the Dead', 'Orson Scott Card', 'science-fiction', 13.75, 5),
(21, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'science-fiction', 8.50, 22),
(22, 'The Restaurant at the End of the Universe', 'Douglas Adams', 'science-fiction', 9.00, 10),
(23, 'Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 'science-fiction', 11.50, 13),
(24, 'A Scanner Darkly', 'Philip K. Dick', 'science-fiction', 10.25, 0),
(25, 'The Three-Body Problem', 'Cixin Liu', 'science-fiction', 19.00, 16),
(26, 'The Dark Forest', 'Cixin Liu', 'science-fiction', 19.50, 8),
(27, 'Death''s End', 'Cixin Liu', 'science-fiction', 20.00, 0),
(28, '1984', 'George Orwell', 'dystopia', 8.99, 28),
(29, 'Animal Farm', 'George Orwell', 'dystopia', 7.50, 17),
(30, 'Brave New World', 'Aldous Huxley', 'dystopia', 9.25, 21),
(31, 'Fahrenheit 451', 'Ray Bradbury', 'dystopia', 9.75, 0),
(32, 'The Handmaid''s Tale', 'Margaret Atwood', 'dystopia', 12.00, 15),
(33, 'The Road', 'Cormac McCarthy', 'post-apocalyptic', 11.25, 6),
(34, 'Station Eleven', 'Emily St. John Mandel', 'post-apocalyptic', 10.50, 9),
(35, 'Parable of the Sower', 'Octavia E. Butler', 'post-apocalyptic', 12.50, 0),
(36, 'The Name of the Wind', 'Patrick Rothfuss', 'fantasy', 14.99, 19),
(37, 'The Wise Man''s Fear', 'Patrick Rothfuss', 'fantasy', 16.50, 4),
(38, 'A Game of Thrones', 'George R.R. Martin', 'fantasy', 18.00, 24),
(39, 'A Clash of Kings', 'George R.R. Martin', 'fantasy', 18.50, 12),
(40, 'A Storm of Swords', 'George R.R. Martin', 'fantasy', 19.25, 0),
(41, 'The Hobbit', 'J.R.R. Tolkien', 'fantasy', 10.99, 30),
(42, 'The Fellowship of the Ring', 'J.R.R. Tolkien', 'fantasy', 12.99, 26),
(43, 'The Two Towers', 'J.R.R. Tolkien', 'fantasy', 12.99, 0),
(44, 'Mistborn: The Final Empire', 'Brandon Sanderson', 'fantasy', 13.50, 14),
(45, 'The Way of Kings', 'Brandon Sanderson', 'fantasy', 17.99, 7),
(46, 'The Martian', 'Andy Weir', 'science-fiction', 10.00, 23),
(47, 'Project Hail Mary', 'Andy Weir', 'science-fiction', 16.00, 11),
(48, 'Red Mars', 'Kim Stanley Robinson', 'science-fiction', 14.00, 0),
(49, 'Green Mars', 'Kim Stanley Robinson', 'science-fiction', 14.50, 1),
(50, 'Blue Mars', 'Kim Stanley Robinson', 'science-fiction', 15.00, 2),
(51, 'Solaris', 'Stanislaw Lem', 'science-fiction', 11.00, 8),
(52, 'Piranesi', 'Susanna Clarke', 'fantasy', 13.00, 0);