// build.mjs — Genera el worker del kit BYOA a partir de kit.config.json + content/.
// Patron identico a shop/build.mjs: hashes calculados del contenido REAL, worker
// autogenerado (no editar a mano). El publisher edita content/ y este build.

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, "content");
const read = (f) => readFileSync(join(contentDir, f), "utf8");

const config = JSON.parse(readFileSync(join(__dirname, "kit.config.json"), "utf8"));
const SKILLS = config.skills;

// Attestations (opcional): content/attestations.json se sirve en well-known.
const attestationsPath = join(contentDir, "attestations.json");
const attestationsJson = existsSync(attestationsPath) ? readFileSync(attestationsPath, "utf8").trim() : null;

const skills = {};
for (const name of SKILLS) {
  const tool = read(`${name}.tool.js`);
  const skillMd = read(`${name}.SKILL.md`);
  skills[name] = {
    tool,
    skillMd,
    hash: createHash("sha256").update(Buffer.from(tool, "utf8")).digest("hex"),
    skillHash: createHash("sha256").update(Buffer.from(skillMd, "utf8")).digest("hex"),
  };
}

const seed = JSON.parse(readFileSync(join(__dirname, "seed.json"), "utf8"));

// --- llms.txt (v0.4) -----------------------------------------------------------
const skillDescriptions = {
  list_items: `List ${config.entity.plural} (filter by text, limit 10). Returns live rows from D1.`,
  get_item: `Get full details of one ${config.entity.singular} by id. Returns {found:false} if unknown.`,
  create_item: `Create a new ${config.entity.singular}. REAL-WORLD EFFECT: confirm name and price with the human first, then POST. Returns the created row with its id.`,
};
const llmsTxt =
  `# ${config.name}\n\n` +
  `> ${config.description} Read tools are public; create_* is a real-world effect and always asks the human first. Static discovery with verified hashes: your agent verifies every tool before running it.\n\n` +
  `## Skills\n\n` +
  SKILLS.map((name) => {
    const title = skillDescriptions[name] || `Skill ${name}.`;
    return `- [${name}](/skills/${name}/SKILL.md): ${title} <!-- skill: {"version":"1.0.0","sha256":"${skills[name].skillHash}","tool":"/skills/${name}/tool.js","tool_sha256":"${skills[name].hash}"} -->\n`;
  }).join("");

// --- landing ---------------------------------------------------------------------
const docLinks = SKILLS.map(
  (name) => `      <li><code>${name}</code> — <a href="/skills/${name}/SKILL.md">SKILL.md</a> · <a href="/skills/${name}/tool.js">tool.js</a></li>`
).join("\n");
const seedRows = seed.map(
  (p) => `      <tr><td>${p.id ?? "-"}</td><td>${p.name}</td><td>$${Number(p.price).toFixed(2)}</td><td>${p.stock}</td></tr>`
).join("\n");
const landing =
  `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n` +
  `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
  `<title>${config.name} — BYOA platform</title>\n` +
  `<style>body{font-family:system-ui,sans-serif;max-width:52rem;margin:2rem auto;padding:0 1rem;line-height:1.55;color:#14181f;background:#fafbfc}code{background:#eef1f4;padding:.1rem .35rem;border-radius:4px;font-size:.92em}a{color:#0b62a4}h1{border-bottom:2px solid #e4e8ec;padding-bottom:.4rem}table{border-collapse:collapse;width:100%;margin:1rem 0}td,th{border:1px solid #e4e8ec;padding:.45rem .6rem;text-align:left;font-size:.95rem}th{background:#eef1f4}pre{background:#14181f;color:#d7e2ec;padding:.8rem 1rem;border-radius:8px;overflow-x:auto}footer{margin-top:2.5rem;color:#66707b;font-size:.9rem;border-top:1px solid #e4e8ec;padding-top:1rem}</style>\n` +
  `</head>\n<body>\n` +
  `<h1>${config.name}</h1>\n` +
  `<p>${config.description} Built with the <strong>BYOA kit</strong> on <a href="https://github.com/MauricioPerera/mcpwasm">mcpwasm</a>: static discovery with verified hashes, tools that run sandboxed on the consumer's machine, and the human holding the approval pen.</p>\n` +
  `<h2>Point your agent here</h2>\n` +
  `<pre>npx -y @rckflr/mcpwasm ${config.origin}</pre>\n` +
  `<h2>Skills</h2>\n<ul>\n${docLinks}\n  </ul>\n` +
  `<h2>Seed ${config.entity.plural}</h2>\n<table>\n      <tr><th>id</th><th>name</th><th>price</th><th>stock</th></tr>\n${seedRows}\n    </table>\n` +
  `<footer>Generated by byoa-kit/build.mjs — do not edit the worker by hand.</footer>\n</body>\n</html>`;

// --- worker autogenerado ---------------------------------------------------------
const toolConstants = SKILLS.map(
  (name) => `const ${name.toUpperCase()}_TOOL_JS = ${JSON.stringify(skills[name].tool)};\n` +
    `const ${name.toUpperCase()}_SKILL_MD = ${JSON.stringify(skills[name].skillMd)};`
).join("\n");

const skillRoutes = SKILLS.map(
  (name) => `  if (path === "/skills/${name}/tool.js") return new Response(${name.toUpperCase()}_TOOL_JS, { headers: { "content-type": "application/javascript; charset=utf-8" } });\n` +
    `  if (path === "/skills/${name}/SKILL.md") return new Response(${name.toUpperCase()}_SKILL_MD, { headers: { "content-type": "text/markdown; charset=utf-8" } });`
).join("\n");

const attestationsRoute = attestationsJson
  ? "  if (path === \"/.well-known/agent-skills/attestations.json\") {\n" +
    "    return new Response(JSON.stringify(ATTESTATIONS), { headers: { \"content-type\": \"application/json; charset=utf-8\", \"cache-control\": \"no-store\" } });\n" +
    "  }\n\n"
  : "";

const worker =
  `// Autogenerado por byoa-kit/build.mjs — NO EDITAR A MANO.\n\n` +
  toolConstants + "\n\n" +
  `const LLMS_TXT = ${JSON.stringify(llmsTxt)};\n\n` +
  `const LANDING = ${JSON.stringify(landing)};\n\n` +
  (attestationsJson ? `const ATTESTATIONS = ${JSON.stringify(JSON.parse(attestationsJson))};\n\n` : "") +
  `function json(obj, status = 200) {\n` +
  `  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json; charset=utf-8" } });\n` +
  `}\n\n` +
  `async function handleListItems(url, env) {\n` +
  `  const q = (url.searchParams.get("q") || "").trim().toLowerCase();\n` +
  `  const limitRaw = Number(url.searchParams.get("limit"));\n` +
  `  const limit = Number.isFinite(limitRaw) && limitRaw >= 1 && limitRaw <= 50 ? Math.floor(limitRaw) : 10;\n` +
  `  let sql = "SELECT id, name, description, price, stock FROM items";\n` +
  `  const params = [];\n` +
  `  if (q) { sql += " WHERE LOWER(name) LIKE LOWER(?) OR LOWER(description) LIKE LOWER(?)"; params.push("%" + q + "%", "%" + q + "%"); }\n` +
  `  sql += " ORDER BY id LIMIT ?"; params.push(limit);\n` +
  `  const { results } = await env.DB.prepare(sql).bind(...params).all();\n` +
  `  return json(results);\n` +
  `}\n\n` +
  `async function handleGetItem(id, env) {\n` +
  `  const item = await env.DB.prepare("SELECT id, name, description, price, stock FROM items WHERE id = ?").bind(id).first();\n` +
  `  if (!item) return json({ found: false }, 404);\n` +
  `  return json(Object.assign({ found: true }, item));\n` +
  `}\n\n` +
  `async function handleCreateItem(request, env) {\n` +
  `  let body;\n` +
  `  try { body = await request.json(); } catch { return json({ error: "Invalid JSON body" }, 400); }\n` +
  `  const name = body && body.name;\n` +
  `  const price = body && body.price;\n` +
  `  const stock = body && typeof body.stock === "number" ? body.stock : 0;\n` +
  `  if (typeof name !== "string" || name.trim().length === 0) return json({ error: "name required" }, 400);\n` +
  `  if (typeof price !== "number" || !Number.isFinite(price) || price < 0) return json({ error: "price must be a number >= 0" }, 400);\n` +
  `  const { meta } = await env.DB.prepare("INSERT INTO items (name, description, price, stock) VALUES (?, ?, ?, ?)")\n` +
  `    .bind(name, typeof body.description === "string" ? body.description : "", price, stock).run();\n` +
  `  const row = await env.DB.prepare("SELECT id, name, description, price, stock FROM items WHERE id = ?").bind(meta.last_row_id).first();\n` +
  `  return json(Object.assign({ ok: true }, row), 201);\n` +
  `}\n\n` +
  `export default {\n` +
  `  async fetch(request, env) {\n` +
  `    const url = new URL(request.url);\n` +
  `    const path = url.pathname;\n` +
  `    if (path === "/") return new Response(LANDING, { headers: { "content-type": "text/html; charset=utf-8" } });\n` +
  `    if (path === "/llms.txt") return new Response(LLMS_TXT, { headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } });\n` +
  attestationsRoute +
  skillRoutes + "\n" +
  `    if (path === "/api/${config.entity.plural}" && request.method === "GET") return await handleListItems(url, env);\n` +
  `    if (path === "/api/${config.entity.plural}" && request.method === "POST") return await handleCreateItem(request, env);\n` +
  `    const idMatch = path.match(/^\\/api\\/${config.entity.plural}\\/(\\d+)$/);\n` +
  `    if (idMatch && request.method === "GET") return await handleGetItem(Number(idMatch[1]), env);\n` +
  `    if (path === "/") return new Response(LANDING, { headers: { "content-type": "text/html; charset=utf-8" } });\n` +
  `    return json({ error: "not found" }, 404);\n` +
  `  }\n` +
  `};\n`;

writeFileSync(join(__dirname, "worker.mjs"), worker, "utf8");
console.log(`Generated: byoa-kit/worker.mjs (${SKILLS.length} skills)`);
for (const name of SKILLS) console.log(`  ${name}: tool_sha256=${skills[name].hash.slice(0, 16)}...`);
if (!attestationsJson) console.log("  (sin attestations — corre scripts/attest.mjs sign para firmarlas)");